---
- name: NGINX | Install and configure NGINX
  hosts: nginx
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:
    - name: update
      ansible.builtin.apt:
        update_cache=yes
    
    - name: NGINX | Install NGINX
      ansible.builtin.apt:
        name: nginx
        state: latest
      notify:
        - restart nginx

    - name: NGINX | Create NGINX config file from template
      ansible.builtin.template:
        src: ./templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - reload nginx
      tags:
        - nginx-configuration


  handlers:
    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes
      
    - name: reload nginx
      ansible.builtin.systemd:
        name: nginx
        state: reloaded
